version: "3.3"
services:
  myproject:
      container_name: myproject
      build: .
      restart: always
      ports:
        - "5000:5000"
      env_file:
        - ./env_variables.env
      external_links:
        - mongo